services:

  # Backend API (Database removed)
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - ENCRYPTION_KEY=your-32-char-encryption-key-here
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your-email@gmail.com
      - SMTP_PASSWORD=your-app-password
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "8000:8000"
    volumes:
      - ./packages/backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend React App
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000

  # Celery Worker for background tasks
  celery-worker:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/metrics_dashboard
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-in-production
      - ENCRYPTION_KEY=your-32-char-encryption-key-here
      - N8N_BASE_URL=http://host.docker.internal:5678
      - N8N_API_KEY=your-n8n-api-key
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./packages/backend:/app
    command: celery -A app.core.celery_app worker --loglevel=info

  # Celery Beat Scheduler
  celery-beat:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/metrics_dashboard
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-in-production
      - ENCRYPTION_KEY=your-32-char-encryption-key-here
      - N8N_BASE_URL=http://host.docker.internal:5678
      - N8N_API_KEY=your-n8n-api-key
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./packages/backend:/app
    command: celery -A app.core.celery_app beat --loglevel=info

  # Celery Flower - Task Monitoring
  celery-flower:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./packages/backend:/app
    command: celery -A app.core.celery_app flower --port=5555

volumes:
  postgres_data:
  redis_data: