"""add_client_validation_indexes

Revision ID: 1aef9c23725d
Revises: 576121956f97
Create Date: 2025-09-04 09:07:57.954223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aef9c23725d'
down_revision = '576121956f97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###