"""add_incremental_sync_fields_to_vistara_workflows

Revision ID: 445776a318f8
Revises: c22a60770222
Create Date: 2025-09-11 13:41:56.331873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445776a318f8'
down_revision = 'c22a60770222'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server defaults to handle existing rows
    op.add_column('vistara_workflows', sa.Column('baseline_total_executions', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('vistara_workflows', sa.Column('baseline_successful_executions', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('vistara_workflows', sa.Column('baseline_failed_executions', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('vistara_workflows', sa.Column('baseline_avg_execution_time_ms', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('vistara_workflows', sa.Column('manual_total_executions_adjustment', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('vistara_workflows', sa.Column('manual_successful_executions_adjustment', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('vistara_workflows', sa.Column('manual_failed_executions_adjustment', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vistara_workflows', 'manual_failed_executions_adjustment')
    op.drop_column('vistara_workflows', 'manual_successful_executions_adjustment')
    op.drop_column('vistara_workflows', 'manual_total_executions_adjustment')
    op.drop_column('vistara_workflows', 'baseline_avg_execution_time_ms')
    op.drop_column('vistara_workflows', 'baseline_failed_executions')
    op.drop_column('vistara_workflows', 'baseline_successful_executions')
    op.drop_column('vistara_workflows', 'baseline_total_executions')
    # ### end Alembic commands ###