"""add_title_column_to_dependencies

Revision ID: 89e72050d105
Revises: 1aef9c23725d
Create Date: 2025-09-05 07:29:23.987918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e72050d105'
down_revision = '1aef9c23725d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('dependencies', sa.Column('title', sa.String(length=255), nullable=True, comment='Display title for the guide'))
    
    # Update existing rows to use platform_name as title if title is null
    op.execute("UPDATE dependencies SET title = platform_name WHERE title IS NULL")
    
    # Now make the column not nullable
    op.alter_column('dependencies', 'title', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependencies', 'title')
    # ### end Alembic commands ###